lang: "en" # Set to your desired console language - see list in lang folder

rewards:
  enabled: true # Master toggle to enable/disable the rewards system
  broadcast: true # Whether to broadcast messages to the server when rewards are given
  reward-cooldown: 60 # Minimum time (in seconds) between processing rewards for the same player

playtime:
  auto-save-interval: 300  # How often (in seconds) playtime data is auto-saved to the database
  page-size: 10 # How many players per page in /pttop
  
track-afk:
  enabled: false  # If true, afk-time is recorded causing play time to be paused when user is AFK
  afk-detection: 300000 # Time (in miliseconds) until player becomes AFK - default is 5 minutes

commands:
  pt:
    enabled: true  # Enable/disable the /pt (playtime) command
  pttop:
    enabled: true  # Enable/disable the /pttop command
  ptreload:
    enabled: true # Enable/disable the /ptreload command

logging:
  debug: false  # Enable debug logging
  reward-claims: true  # Log every reward claim to the server console
  
color: # Set the visual colors - use Minecraft chat codes (1.16 or below) e.g. &c or hex codes e.g. #FF5555 (1.16+)
  integer: "#FFFFFF" # Numbers used in total play time
  interval: "#55FF55" # Words following integer e.g. month
  header: "#FFAA00" # Color of the top bar in /pttop
  footer: "#FFAA00" # Color of the bottom bar in /pttop
  list-item: "#FFFFFF" # List number on /pttop
  error: "#FF5555" # Any error message
  success: "#55FF55" # Any success message
  user: "#FFFFFF" # Any username
  earned: "#FFFFFF" # Reward message e.g. "...has earned"
  reward: "#FFFFFF" # Name of reward
