lang: "en" # Set to your desired language - see list in lang folder

rewards:
  enabled: true # Master toggle to enable/disable the rewards system
  broadcast: true # Whether to broadcast messages to the server when rewards are given
  reward-cooldown: 60 # Minimum time (in seconds) between processing rewards for the same player

playtime:
  auto-save-interval: 300  # How often (in seconds) playtime data is auto-saved to the database
  
track-afk:
  enabled: false  # If true, afk-time is recorded causing play time to be paused when user is AFK
  afk-detection: 300000 # Time (in miliseconds) until player becomes AFK - default is 5 minutes

commands:
  pt:
    enabled: true  # Enable/disable the /pt (playtime) command
    permission: "playtime.check"  # Required permission to use /pt
  pttop:
    enabled: true  # Enable/disable the /pttop command
    permission: "playtime.top"  # Required permission to view the top playtimes
  ptreload:
    enabled: true
    permission: "playtime.reload" # Required permission to reload the config

logging:
  debug: false  # Enable debug logging
  reward-claims: true  # Log every reward claim to the server console